version: '3.4'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    user: ${MY_UID:-1000}
    volumes:
      - ./:/app
    working_dir: /app
    command: 'php -S 0.0.0.0:8080 -t /app/public'
    ports:
      - "80:8080"
  ws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    user: ${MY_UID:-1000}
    volumes:
      - ./:/app
    working_dir: /app
    command: 'php bin/console gos:websocket:server'
    ports:
      - "8080:${GOS_WEB_SOCKET_SERVER_PORT}"
  cli:
    image: edbizarro/gitlab-ci-pipeline-php:8.0
    volumes:
      - ./:/app
    user: ${MY_UID:-1000}
    tty: true
    working_dir: /app
