version: '3.4'
services:
   php:
     image: php:7.2-cli
     volumes:
       - ./:/app
     working_dir: /app
     command: 'php index.php'
     depends_on:
       - tor
     links:
       - tor
   tor:
     image: peterdavehello/tor-socks-proxy:latest
