version: '3.4'
services:
  mysql:
      image: mysql:5.7
      volumes:
          - mysqldata:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbname
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: userpassword
      command: --tmp_table_size=32M --max_heap_table_size=32M
      ports:
          - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links:
        - mysql
    environment:
        - PMA_HOST=mysql
    ports:
      - "80:80"
  cli:
    image: edbizarro/gitlab-ci-pipeline-php:8.0
    volumes:
        - ./:/var/www/html
    user: ${MY_UID:-1000}
    tty: true
    working_dir: /var/www/html
volumes:
  mysqldata:
