version: '3.4'
services:
  php:
    image: php:8.0-cli
    volumes:
        - ./:/app
    working_dir: /app
    command: 'php -a'
    user: ${MY_UID:-1000}
    tty: true
  # at the moment cli container use 8.1.1, but Symfony 6 requires at least 8.0.2
  cli:
      image: edbizarro/gitlab-ci-pipeline-php:8.0
      volumes:
          - ./:/app
      user: ${MY_UID:-1000}
      tty: true
      working_dir: /app
