version: '3'
services:
    symfony:
        build: .
        volumes:
          - ./:/app
        depends_on:
          - mysql
        links:
          - mysql
        labels:
          traefik.backend: "symfony"
          traefik.frontend.rule: "Host:symfony3.lvh.me"
        environment:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${COMPOSER_GITHUB_OUATH}"}}'
          PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
          XDEBUG_CONFIG: "remote_host=${MY_IP}"
    mysql:
        image: mysql:5.6
        volumes:
            - ./var/.docker-runtime/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfonypassword
        ports:
            - "3307:3306"
    traefik:
        image: traefik
        command: --web --docker --logLevel=DEBUG
        ports:
          - "80:80"
          - "8080:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /dev/null:/etc/traefik/traefik.toml
