# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $sqsUrl: '%env(AWS_SQS_URL)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    aws_sdk:
        class: Aws\Sdk
        arguments:
            $args:
                region: eu-central-1
                http:
#                    verify: /home/marcin/.local/mitmproxy/mitmproxy-ca-cert.pem
#                    proxy: http://127.0.0.1:8080
    Aws\Sdk: '@aws_sdk'
    Aws\CloudWatch\CloudWatchClient:
        factory: [ '@aws_sdk', 'createCloudWatch' ]
        arguments:
              - version: '2010-08-01'
    Aws\Sqs\SqsClient:
        factory: [ '@aws_sdk', 'createSqs' ]
        arguments:
            - version: '2012-11-05'
    Aws\EventBridge\EventBridgeClient:
        factory: [ '@aws_sdk', 'createEventBridge' ]
        arguments:
            - version: '2015-10-07'
    Aws\SecretsManager\SecretsManagerClient:
        factory: [ '@aws_sdk', 'createSecretsManager' ]
        arguments:
            - version: '2017-10-17'
    Aws\Ssm\SsmClient:
        factory: [ '@aws_sdk', 'createSsm' ]
        arguments:
            - version: '2014-11-06'
    Aws\S3\S3Client:
            factory: [ '@aws_sdk', 'createS3' ]
            arguments:
                - version: '2006-03-01'
    Aws\CloudWatchLogs\CloudWatchLogsClient:
        factory: [ '@aws_sdk', 'createCloudWatchLogs' ]
        arguments:
            - version: '2014-03-28'
    Aws\Polly\PollyClient:
        factory: [ '@aws_sdk', 'createPolly' ]
        arguments:
            - version: '2016-06-10'
    Aws\MediaConvert\MediaConvertClient:
        factory: [ '\App\MediaConvertFactory', 'factoryMediaConvert' ]
        arguments:
            - '@aws_sdk'
            - version: '2017-08-29'
